#! /bin/sh 
for f in "$1"/*; do
  if [ -f "$f" ]; then
    SIZE="$(du -sh "${f}" | cut -f1)"
    echo "Processing $f file..."
    echo "$SIZE"

  fi
     if [ -f "$f" ]; then  
       WORD_COUNT="$(wc -w "${f}" | cut -f1)"
       echo "WORDS: $WORD_COUNT"
     fi
done


